esphome:
  name: esp-camera-01

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "G7lOkxF6DAJQ6sptPTWVPYY07otCf1Fx0lpP1YenbCE="

ota:
  password: "fbfa3d12eb557d008b15a0e50e88a13f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.31.9
    gateway: 192.168.31.1
    subnet: 255.255.255.0
    dns1: 192.168.31.1
    dns2: 1.1.1.1
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Kamera-01 Fallback Hotspot"
    password: "YLs1xlK1E2DW"
  fast_connect: True

captive_portal:
web_server:
  port: 80

switch:
  - platform: gpio
    pin: D3
    name: "Shutter"
    id: shutter
    on_turn_on:
     - delay: 500ms
     - switch.turn_off: shutter
    restore_mode: ALWAYS_OFF
  - platform: restart
    name: "Esp Camera 01 Restart"

sensor:
  - platform: uptime
    name: Camera 01 Uptime Sensor
    id: camera01_uptime_sensor
    update_interval: 5s